name: team_8
services:

  db:
    image: postgres:16
    container_name: team8-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - team8_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18
    container_name: team8-odoo
    depends_on:
      - db
    ports:
      - "8076:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - team8_odoo_data:/var/lib/odoo
      - .:/mnt/extra-addons/networkPilotNew
    restart: unless-stopped

volumes:
  team8_db_data:
  team8_odoo_data:
